import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "./Providers";
import NavBar from "@/components/headerWrapper";
import Footer from "@/components/footerWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Job Portal Website ",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AuthProvider>
            <NavBar/>
            {children}
            <Footer/>
          </AuthProvider>
        </body>
      </html>
    </>
  );
}
