export const categories = [
  { name: 'Creative & Design', icon: '/catagory/creativeIdea.png' },
  { name: 'Education & Training', icon: '/catagory/education.png' },
  { name: 'Technology & Development', icon: '/catagory/technology.png' },
  { name: 'Operations & Logistics', icon: '/catagory/operation.png' },
  { name: 'Marketing & Sales', icon: '/catagory/marketing.png' },
  { name: 'Creative & Design', icon: '/catagory/creativeIdea.png' },
  { name: 'Education & Training', icon: '/catagory/education.png' },
  { name: 'Technology & Development', icon: '/catagory/technology.png' },
  { name: 'Operations & Logistics', icon: '/catagory/operation.png' },
  { name: 'Marketing & Sales', icon: '/catagory/marketing.png' },
  { name: 'Creative & Design', icon: '/catagory/creativeIdea.png' },
  { name: 'Education & Training', icon: '/catagory/education.png' },
  { name: 'Technology & Development', icon: '/catagory/technology.png' },
  { name: 'Operations & Logistics', icon: '/catagory/operation.png' },
  { name: 'Marketing & Sales', icon: '/catagory/marketing.png' },
  { name: 'Creative & Design', icon: '/catagory/creativeIdea.png' },
  { name: 'Education & Training', icon: '/catagory/education.png' },
  { name: 'Technology & Development', icon: '/catagory/technology.png' },
  { name: 'Operations & Logistics', icon: '/catagory/operation.png' },
  { name: 'Marketing & Sales', icon: '/catagory/marketing.png' },
  { name: 'Creative & Design', icon: '/catagory/creativeIdea.png' },
  { name: 'Education & Training', icon: '/catagory/education.png' },
  { name: 'Technology & Development', icon: '/catagory/technology.png' },
  { name: 'Operations & Logistics', icon: '/catagory/operation.png' },
  { name: 'Marketing & Sales', icon: '/catagory/marketing.png' },
];