export const countries = [
  // Sri Lanka at the top
  {
    value: "LK",
    label: "Sri Lanka",
    code: "lk",
    flag: "https://flagcdn.com/w20/lk.png",
  },

  // All other countries alphabetically
  {
    value: "AF",
    label: "Afghanistan",
    code: "af",
    flag: "https://flagcdn.com/w20/af.png",
  },
  {
    value: "AL",
    label: "Albania",
    code: "al",
    flag: "https://flagcdn.com/w20/al.png",
  },
  {
    value: "DZ",
    label: "Algeria",
    code: "dz",
    flag: "https://flagcdn.com/w20/dz.png",
  },
  {
    value: "AD",
    label: "Andorra",
    code: "ad",
    flag: "https://flagcdn.com/w20/ad.png",
  },
  {
    value: "AO",
    label: "Angola",
    code: "ao",
    flag: "https://flagcdn.com/w20/ao.png",
  },
  {
    value: "AR",
    label: "Argentina",
    code: "ar",
    flag: "https://flagcdn.com/w20/ar.png",
  },
  {
    value: "AM",
    label: "Armenia",
    code: "am",
    flag: "https://flagcdn.com/w20/am.png",
  },
  {
    value: "AU",
    label: "Australia",
    code: "au",
    flag: "https://flagcdn.com/w20/au.png",
  },
  {
    value: "AT",
    label: "Austria",
    code: "at",
    flag: "https://flagcdn.com/w20/at.png",
  },
  {
    value: "AZ",
    label: "Azerbaijan",
    code: "az",
    flag: "https://flagcdn.com/w20/az.png",
  },
  {
    value: "BS",
    label: "Bahamas",
    code: "bs",
    flag: "https://flagcdn.com/w20/bs.png",
  },
  {
    value: "BH",
    label: "Bahrain",
    code: "bh",
    flag: "https://flagcdn.com/w20/bh.png",
  },
  {
    value: "BD",
    label: "Bangladesh",
    code: "bd",
    flag: "https://flagcdn.com/w20/bd.png",
  },
  {
    value: "BB",
    label: "Barbados",
    code: "bb",
    flag: "https://flagcdn.com/w20/bb.png",
  },
  {
    value: "BY",
    label: "Belarus",
    code: "by",
    flag: "https://flagcdn.com/w20/by.png",
  },
  {
    value: "BE",
    label: "Belgium",
    code: "be",
    flag: "https://flagcdn.com/w20/be.png",
  },
  {
    value: "BZ",
    label: "Belize",
    code: "bz",
    flag: "https://flagcdn.com/w20/bz.png",
  },
  {
    value: "BJ",
    label: "Benin",
    code: "bj",
    flag: "https://flagcdn.com/w20/bj.png",
  },
  {
    value: "BT",
    label: "Bhutan",
    code: "bt",
    flag: "https://flagcdn.com/w20/bt.png",
  },
  {
    value: "BO",
    label: "Bolivia",
    code: "bo",
    flag: "https://flagcdn.com/w20/bo.png",
  },
  {
    value: "BA",
    label: "Bosnia and Herzegovina",
    code: "ba",
    flag: "https://flagcdn.com/w20/ba.png",
  },
  {
    value: "BW",
    label: "Botswana",
    code: "bw",
    flag: "https://flagcdn.com/w20/bw.png",
  },
  {
    value: "BR",
    label: "Brazil",
    code: "br",
    flag: "https://flagcdn.com/w20/br.png",
  },
  {
    value: "BN",
    label: "Brunei",
    code: "bn",
    flag: "https://flagcdn.com/w20/bn.png",
  },
  {
    value: "BG",
    label: "Bulgaria",
    code: "bg",
    flag: "https://flagcdn.com/w20/bg.png",
  },
  {
    value: "BF",
    label: "Burkina Faso",
    code: "bf",
    flag: "https://flagcdn.com/w20/bf.png",
  },
  {
    value: "BI",
    label: "Burundi",
    code: "bi",
    flag: "https://flagcdn.com/w20/bi.png",
  },
  {
    value: "KH",
    label: "Cambodia",
    code: "kh",
    flag: "https://flagcdn.com/w20/kh.png",
  },
  {
    value: "CM",
    label: "Cameroon",
    code: "cm",
    flag: "https://flagcdn.com/w20/cm.png",
  },
  {
    value: "CA",
    label: "Canada",
    code: "ca",
    flag: "https://flagcdn.com/w20/ca.png",
  },
  {
    value: "CV",
    label: "Cape Verde",
    code: "cv",
    flag: "https://flagcdn.com/w20/cv.png",
  },
  {
    value: "TD",
    label: "Chad",
    code: "td",
    flag: "https://flagcdn.com/w20/td.png",
  },
  {
    value: "CL",
    label: "Chile",
    code: "cl",
    flag: "https://flagcdn.com/w20/cl.png",
  },
  {
    value: "CN",
    label: "China",
    code: "cn",
    flag: "https://flagcdn.com/w20/cn.png",
  },
  {
    value: "CO",
    label: "Colombia",
    code: "co",
    flag: "https://flagcdn.com/w20/co.png",
  },
  {
    value: "CR",
    label: "Costa Rica",
    code: "cr",
    flag: "https://flagcdn.com/w20/cr.png",
  },
  {
    value: "CI",
    label: "Côte d'Ivoire",
    code: "ci",
    flag: "https://flagcdn.com/w20/ci.png",
  },
  {
    value: "HR",
    label: "Croatia",
    code: "hr",
    flag: "https://flagcdn.com/w20/hr.png",
  },
  {
    value: "CU",
    label: "Cuba",
    code: "cu",
    flag: "https://flagcdn.com/w20/cu.png",
  },
  {
    value: "CY",
    label: "Cyprus",
    code: "cy",
    flag: "https://flagcdn.com/w20/cy.png",
  },
  {
    value: "CZ",
    label: "Czech Republic",
    code: "cz",
    flag: "https://flagcdn.com/w20/cz.png",
  },
  {
    value: "CD",
    label: "Democratic Republic of the Congo",
    code: "cd",
    flag: "https://flagcdn.com/w20/cd.png",
  },
  {
    value: "DK",
    label: "Denmark",
    code: "dk",
    flag: "https://flagcdn.com/w20/dk.png",
  },
  {
    value: "DJ",
    label: "Djibouti",
    code: "dj",
    flag: "https://flagcdn.com/w20/dj.png",
  },
  {
    value: "DO",
    label: "Dominican Republic",
    code: "do",
    flag: "https://flagcdn.com/w20/do.png",
  },
  {
    value: "EC",
    label: "Ecuador",
    code: "ec",
    flag: "https://flagcdn.com/w20/ec.png",
  },
  {
    value: "EG",
    label: "Egypt",
    code: "eg",
    flag: "https://flagcdn.com/w20/eg.png",
  },
  {
    value: "SV",
    label: "El Salvador",
    code: "sv",
    flag: "https://flagcdn.com/w20/sv.png",
  },
  {
    value: "GQ",
    label: "Equatorial Guinea",
    code: "gq",
    flag: "https://flagcdn.com/w20/gq.png",
  },
  {
    value: "ER",
    label: "Eritrea",
    code: "er",
    flag: "https://flagcdn.com/w20/er.png",
  },
  {
    value: "EE",
    label: "Estonia",
    code: "ee",
    flag: "https://flagcdn.com/w20/ee.png",
  },
  {
    value: "ET",
    label: "Ethiopia",
    code: "et",
    flag: "https://flagcdn.com/w20/et.png",
  },
  {
    value: "FJ",
    label: "Fiji",
    code: "fj",
    flag: "https://flagcdn.com/w20/fj.png",
  },
  {
    value: "FI",
    label: "Finland",
    code: "fi",
    flag: "https://flagcdn.com/w20/fi.png",
  },
  {
    value: "FR",
    label: "France",
    code: "fr",
    flag: "https://flagcdn.com/w20/fr.png",
  },
  {
    value: "GA",
    label: "Gabon",
    code: "ga",
    flag: "https://flagcdn.com/w20/ga.png",
  },
  {
    value: "GM",
    label: "Gambia",
    code: "gm",
    flag: "https://flagcdn.com/w20/gm.png",
  },
  {
    value: "GE",
    label: "Georgia",
    code: "ge",
    flag: "https://flagcdn.com/w20/ge.png",
  },
  {
    value: "DE",
    label: "Germany",
    code: "de",
    flag: "https://flagcdn.com/w20/de.png",
  },
  {
    value: "GH",
    label: "Ghana",
    code: "gh",
    flag: "https://flagcdn.com/w20/gh.png",
  },
  {
    value: "GR",
    label: "Greece",
    code: "gr",
    flag: "https://flagcdn.com/w20/gr.png",
  },
  {
    value: "GT",
    label: "Guatemala",
    code: "gt",
    flag: "https://flagcdn.com/w20/gt.png",
  },
  {
    value: "GN",
    label: "Guinea",
    code: "gn",
    flag: "https://flagcdn.com/w20/gn.png",
  },
  {
    value: "GY",
    label: "Guyana",
    code: "gy",
    flag: "https://flagcdn.com/w20/gy.png",
  },
  {
    value: "HT",
    label: "Haiti",
    code: "ht",
    flag: "https://flagcdn.com/w20/ht.png",
  },
  {
    value: "HN",
    label: "Honduras",
    code: "hn",
    flag: "https://flagcdn.com/w20/hn.png",
  },
  {
    value: "HK",
    label: "Hong Kong",
    code: "hk",
    flag: "https://flagcdn.com/w20/hk.png",
  },
  {
    value: "HU",
    label: "Hungary",
    code: "hu",
    flag: "https://flagcdn.com/w20/hu.png",
  },
  {
    value: "IS",
    label: "Iceland",
    code: "is",
    flag: "https://flagcdn.com/w20/is.png",
  },
  {
    value: "IN",
    label: "India",
    code: "in",
    flag: "https://flagcdn.com/w20/in.png",
  },
  {
    value: "ID",
    label: "Indonesia",
    code: "id",
    flag: "https://flagcdn.com/w20/id.png",
  },
  {
    value: "IR",
    label: "Iran",
    code: "ir",
    flag: "https://flagcdn.com/w20/ir.png",
  },
  {
    value: "IQ",
    label: "Iraq",
    code: "iq",
    flag: "https://flagcdn.com/w20/iq.png",
  },
  {
    value: "IE",
    label: "Ireland",
    code: "ie",
    flag: "https://flagcdn.com/w20/ie.png",
  },
  {
    value: "IL",
    label: "Israel",
    code: "il",
    flag: "https://flagcdn.com/w20/il.png",
  },
  {
    value: "IT",
    label: "Italy",
    code: "it",
    flag: "https://flagcdn.com/w20/it.png",
  },
  {
    value: "JM",
    label: "Jamaica",
    code: "jm",
    flag: "https://flagcdn.com/w20/jm.png",
  },
  {
    value: "JP",
    label: "Japan",
    code: "jp",
    flag: "https://flagcdn.com/w20/jp.png",
  },
  {
    value: "JO",
    label: "Jordan",
    code: "jo",
    flag: "https://flagcdn.com/w20/jo.png",
  },
  {
    value: "KZ",
    label: "Kazakhstan",
    code: "kz",
    flag: "https://flagcdn.com/w20/kz.png",
  },
  {
    value: "KE",
    label: "Kenya",
    code: "ke",
    flag: "https://flagcdn.com/w20/ke.png",
  },
  {
    value: "KI",
    label: "Kiribati",
    code: "ki",
    flag: "https://flagcdn.com/w20/ki.png",
  },
  {
    value: "KW",
    label: "Kuwait",
    code: "kw",
    flag: "https://flagcdn.com/w20/kw.png",
  },
  {
    value: "KG",
    label: "Kyrgyzstan",
    code: "kg",
    flag: "https://flagcdn.com/w20/kg.png",
  },
  {
    value: "LA",
    label: "Laos",
    code: "la",
    flag: "https://flagcdn.com/w20/la.png",
  },
  {
    value: "LV",
    label: "Latvia",
    code: "lv",
    flag: "https://flagcdn.com/w20/lv.png",
  },
  {
    value: "LB",
    label: "Lebanon",
    code: "lb",
    flag: "https://flagcdn.com/w20/lb.png",
  },
  {
    value: "LS",
    label: "Lesotho",
    code: "ls",
    flag: "https://flagcdn.com/w20/ls.png",
  },
  {
    value: "LR",
    label: "Liberia",
    code: "lr",
    flag: "https://flagcdn.com/w20/lr.png",
  },
  {
    value: "LY",
    label: "Libya",
    code: "ly",
    flag: "https://flagcdn.com/w20/ly.png",
  },
  {
    value: "LI",
    label: "Liechtenstein",
    code: "li",
    flag: "https://flagcdn.com/w20/li.png",
  },
  {
    value: "LT",
    label: "Lithuania",
    code: "lt",
    flag: "https://flagcdn.com/w20/lt.png",
  },
  {
    value: "LU",
    label: "Luxembourg",
    code: "lu",
    flag: "https://flagcdn.com/w20/lu.png",
  },
  {
    value: "MO",
    label: "Macau",
    code: "mo",
    flag: "https://flagcdn.com/w20/mo.png",
  },
  {
    value: "MG",
    label: "Madagascar",
    code: "mg",
    flag: "https://flagcdn.com/w20/mg.png",
  },
  {
    value: "MW",
    label: "Malawi",
    code: "mw",
    flag: "https://flagcdn.com/w20/mw.png",
  },
  {
    value: "MY",
    label: "Malaysia",
    code: "my",
    flag: "https://flagcdn.com/w20/my.png",
  },
  {
    value: "MV",
    label: "Maldives",
    code: "mv",
    flag: "https://flagcdn.com/w20/mv.png",
  },
  {
    value: "ML",
    label: "Mali",
    code: "ml",
    flag: "https://flagcdn.com/w20/ml.png",
  },
  {
    value: "MT",
    label: "Malta",
    code: "mt",
    flag: "https://flagcdn.com/w20/mt.png",
  },
  {
    value: "MH",
    label: "Marshall Islands",
    code: "mh",
    flag: "https://flagcdn.com/w20/mh.png",
  },
  {
    value: "MR",
    label: "Mauritania",
    code: "mr",
    flag: "https://flagcdn.com/w20/mr.png",
  },
  {
    value: "MU",
    label: "Mauritius",
    code: "mu",
    flag: "https://flagcdn.com/w20/mu.png",
  },
  {
    value: "MX",
    label: "Mexico",
    code: "mx",
    flag: "https://flagcdn.com/w20/mx.png",
  },
  {
    value: "FM",
    label: "Micronesia",
    code: "fm",
    flag: "https://flagcdn.com/w20/fm.png",
  },
  {
    value: "MD",
    label: "Moldova",
    code: "md",
    flag: "https://flagcdn.com/w20/md.png",
  },
  {
    value: "MC",
    label: "Monaco",
    code: "mc",
    flag: "https://flagcdn.com/w20/mc.png",
  },
  {
    value: "MN",
    label: "Mongolia",
    code: "mn",
    flag: "https://flagcdn.com/w20/mn.png",
  },
  {
    value: "ME",
    label: "Montenegro",
    code: "me",
    flag: "https://flagcdn.com/w20/me.png",
  },
  {
    value: "MA",
    label: "Morocco",
    code: "ma",
    flag: "https://flagcdn.com/w20/ma.png",
  },
  {
    value: "MZ",
    label: "Mozambique",
    code: "mz",
    flag: "https://flagcdn.com/w20/mz.png",
  },
  {
    value: "MM",
    label: "Myanmar",
    code: "mm",
    flag: "https://flagcdn.com/w20/mm.png",
  },
  {
    value: "NA",
    label: "Namibia",
    code: "na",
    flag: "https://flagcdn.com/w20/na.png",
  },
  {
    value: "NR",
    label: "Nauru",
    code: "nr",
    flag: "https://flagcdn.com/w20/nr.png",
  },
  {
    value: "NP",
    label: "Nepal",
    code: "np",
    flag: "https://flagcdn.com/w20/np.png",
  },
  {
    value: "NL",
    label: "Netherlands",
    code: "nl",
    flag: "https://flagcdn.com/w20/nl.png",
  },
  {
    value: "NZ",
    label: "New Zealand",
    code: "nz",
    flag: "https://flagcdn.com/w20/nz.png",
  },
  {
    value: "NI",
    label: "Nicaragua",
    code: "ni",
    flag: "https://flagcdn.com/w20/ni.png",
  },
  {
    value: "NE",
    label: "Niger",
    code: "ne",
    flag: "https://flagcdn.com/w20/ne.png",
  },
  {
    value: "NG",
    label: "Nigeria",
    code: "ng",
    flag: "https://flagcdn.com/w20/ng.png",
  },
  {
    value: "KP",
    label: "North Korea",
    code: "kp",
    flag: "https://flagcdn.com/w20/kp.png",
  },
  {
    value: "MK",
    label: "North Macedonia",
    code: "mk",
    flag: "https://flagcdn.com/w20/mk.png",
  },
  {
    value: "NO",
    label: "Norway",
    code: "no",
    flag: "https://flagcdn.com/w20/no.png",
  },
  {
    value: "OM",
    label: "Oman",
    code: "om",
    flag: "https://flagcdn.com/w20/om.png",
  },
  {
    value: "PK",
    label: "Pakistan",
    code: "pk",
    flag: "https://flagcdn.com/w20/pk.png",
  },
  {
    value: "PW",
    label: "Palau",
    code: "pw",
    flag: "https://flagcdn.com/w20/pw.png",
  },
  {
    value: "PS",
    label: "Palestine",
    code: "ps",
    flag: "https://flagcdn.com/w20/ps.png",
  },
  {
    value: "PA",
    label: "Panama",
    code: "pa",
    flag: "https://flagcdn.com/w20/pa.png",
  },
  {
    value: "PG",
    label: "Papua New Guinea",
    code: "pg",
    flag: "https://flagcdn.com/w20/pg.png",
  },
  {
    value: "PY",
    label: "Paraguay",
    code: "py",
    flag: "https://flagcdn.com/w20/py.png",
  },
  {
    value: "PE",
    label: "Peru",
    code: "pe",
    flag: "https://flagcdn.com/w20/pe.png",
  },
  {
    value: "PH",
    label: "Philippines",
    code: "ph",
    flag: "https://flagcdn.com/w20/ph.png",
  },
  {
    value: "PL",
    label: "Poland",
    code: "pl",
    flag: "https://flagcdn.com/w20/pl.png",
  },
  {
    value: "PT",
    label: "Portugal",
    code: "pt",
    flag: "https://flagcdn.com/w20/pt.png",
  },
  {
    value: "QA",
    label: "Qatar",
    code: "qa",
    flag: "https://flagcdn.com/w20/qa.png",
  },
  {
    value: "CG",
    label: "Republic of the Congo",
    code: "cg",
    flag: "https://flagcdn.com/w20/cg.png",
  },
  {
    value: "RO",
    label: "Romania",
    code: "ro",
    flag: "https://flagcdn.com/w20/ro.png",
  },
  {
    value: "RU",
    label: "Russia",
    code: "ru",
    flag: "https://flagcdn.com/w20/ru.png",
  },
  {
    value: "RW",
    label: "Rwanda",
    code: "rw",
    flag: "https://flagcdn.com/w20/rw.png",
  },
  {
    value: "KN",
    label: "Saint Kitts and Nevis",
    code: "kn",
    flag: "https://flagcdn.com/w20/kn.png",
  },
  {
    value: "LC",
    label: "Saint Lucia",
    code: "lc",
    flag: "https://flagcdn.com/w20/lc.png",
  },
  {
    value: "VC",
    label: "Saint Vincent and the Grenadines",
    code: "vc",
    flag: "https://flagcdn.com/w20/vc.png",
  },
  {
    value: "WS",
    label: "Samoa",
    code: "ws",
    flag: "https://flagcdn.com/w20/ws.png",
  },
  {
    value: "SM",
    label: "San Marino",
    code: "sm",
    flag: "https://flagcdn.com/w20/sm.png",
  },
  {
    value: "ST",
    label: "São Tomé and Príncipe",
    code: "st",
    flag: "https://flagcdn.com/w20/st.png",
  },
  {
    value: "SA",
    label: "Saudi Arabia",
    code: "sa",
    flag: "https://flagcdn.com/w20/sa.png",
  },
  {
    value: "SN",
    label: "Senegal",
    code: "sn",
    flag: "https://flagcdn.com/w20/sn.png",
  },
  {
    value: "RS",
    label: "Serbia",
    code: "rs",
    flag: "https://flagcdn.com/w20/rs.png",
  },
  {
    value: "SC",
    label: "Seychelles",
    code: "sc",
    flag: "https://flagcdn.com/w20/sc.png",
  },
  {
    value: "SL",
    label: "Sierra Leone",
    code: "sl",
    flag: "https://flagcdn.com/w20/sl.png",
  },
  {
    value: "SG",
    label: "Singapore",
    code: "sg",
    flag: "https://flagcdn.com/w20/sg.png",
  },
  {
    value: "SK",
    label: "Slovakia",
    code: "sk",
    flag: "https://flagcdn.com/w20/sk.png",
  },
  {
    value: "SI",
    label: "Slovenia",
    code: "si",
    flag: "https://flagcdn.com/w20/si.png",
  },
  {
    value: "SB",
    label: "Solomon Islands",
    code: "sb",
    flag: "https://flagcdn.com/w20/sb.png",
  },
  {
    value: "SO",
    label: "Somalia",
    code: "so",
    flag: "https://flagcdn.com/w20/so.png",
  },
  {
    value: "ZA",
    label: "South Africa",
    code: "za",
    flag: "https://flagcdn.com/w20/za.png",
  },
  {
    value: "KR",
    label: "South Korea",
    code: "kr",
    flag: "https://flagcdn.com/w20/kr.png",
  },
  {
    value: "SS",
    label: "South Sudan",
    code: "ss",
    flag: "https://flagcdn.com/w20/ss.png",
  },
  {
    value: "ES",
    label: "Spain",
    code: "es",
    flag: "https://flagcdn.com/w20/es.png",
  },
  {
    value: "SD",
    label: "Sudan",
    code: "sd",
    flag: "https://flagcdn.com/w20/sd.png",
  },
  {
    value: "SR",
    label: "Suriname",
    code: "sr",
    flag: "https://flagcdn.com/w20/sr.png",
  },
  {
    value: "SZ",
    label: "Swaziland",
    code: "sz",
    flag: "https://flagcdn.com/w20/sz.png",
  },
  {
    value: "SE",
    label: "Sweden",
    code: "se",
    flag: "https://flagcdn.com/w20/se.png",
  },
  {
    value: "CH",
    label: "Switzerland",
    code: "ch",
    flag: "https://flagcdn.com/w20/ch.png",
  },
  {
    value: "SY",
    label: "Syria",
    code: "sy",
    flag: "https://flagcdn.com/w20/sy.png",
  },
  {
    value: "TW",
    label: "Taiwan",
    code: "tw",
    flag: "https://flagcdn.com/w20/tw.png",
  },
  {
    value: "TJ",
    label: "Tajikistan",
    code: "tj",
    flag: "https://flagcdn.com/w20/tj.png",
  },
  {
    value: "TZ",
    label: "Tanzania",
    code: "tz",
    flag: "https://flagcdn.com/w20/tz.png",
  },
  {
    value: "TH",
    label: "Thailand",
    code: "th",
    flag: "https://flagcdn.com/w20/th.png",
  },
  {
    value: "TL",
    label: "Timor-Leste",
    code: "tl",
    flag: "https://flagcdn.com/w20/tl.png",
  },
  {
    value: "TG",
    label: "Togo",
    code: "tg",
    flag: "https://flagcdn.com/w20/tg.png",
  },
  {
    value: "TO",
    label: "Tonga",
    code: "to",
    flag: "https://flagcdn.com/w20/to.png",
  },
  {
    value: "TT",
    label: "Trinidad and Tobago",
    code: "tt",
    flag: "https://flagcdn.com/w20/tt.png",
  },
  {
    value: "TN",
    label: "Tunisia",
    code: "tn",
    flag: "https://flagcdn.com/w20/tn.png",
  },
  {
    value: "TR",
    label: "Turkey",
    code: "tr",
    flag: "https://flagcdn.com/w20/tr.png",
  },
  {
    value: "TM",
    label: "Turkmenistan",
    code: "tm",
    flag: "https://flagcdn.com/w20/tm.png",
  },
  {
    value: "TV",
    label: "Tuvalu",
    code: "tv",
    flag: "https://flagcdn.com/w20/tv.png",
  },
  {
    value: "UG",
    label: "Uganda",
    code: "ug",
    flag: "https://flagcdn.com/w20/ug.png",
  },
  {
    value: "UA",
    label: "Ukraine",
    code: "ua",
    flag: "https://flagcdn.com/w20/ua.png",
  },
  {
    value: "AE",
    label: "United Arab Emirates",
    code: "ae",
    flag: "https://flagcdn.com/w20/ae.png",
  },
  {
    value: "GB",
    label: "United Kingdom",
    code: "gb",
    flag: "https://flagcdn.com/w20/gb.png",
  },
  {
    value: "US",
    label: "United States",
    code: "us",
    flag: "https://flagcdn.com/w20/us.png",
  },
  {
    value: "UY",
    label: "Uruguay",
    code: "uy",
    flag: "https://flagcdn.com/w20/uy.png",
  },
  {
    value: "UZ",
    label: "Uzbekistan",
    code: "uz",
    flag: "https://flagcdn.com/w20/uz.png",
  },
  {
    value: "VU",
    label: "Vanuatu",
    code: "vu",
    flag: "https://flagcdn.com/w20/vu.png",
  },
  {
    value: "VA",
    label: "Vatican City",
    code: "va",
    flag: "https://flagcdn.com/w20/va.png",
  },
  {
    value: "VE",
    label: "Venezuela",
    code: "ve",
    flag: "https://flagcdn.com/w20/ve.png",
  },
  {
    value: "VN",
    label: "Vietnam",
    code: "vn",
    flag: "https://flagcdn.com/w20/vn.png",
  },
  {
    value: "YE",
    label: "Yemen",
    code: "ye",
    flag: "https://flagcdn.com/w20/ye.png",
  },
  {
    value: "ZM",
    label: "Zambia",
    code: "zm",
    flag: "https://flagcdn.com/w20/zm.png",
  },
  {
    value: "ZW",
    label: "Zimbabwe",
    code: "zw",
    flag: "https://flagcdn.com/w20/zw.png",
  },
];
