export const countries = [
    { value: "", label: "Select the Country", code: "", flag: "https://flagcdn.com/w20/us.png" },
    { value: "US", label: "United States", code: "us", flag: "https://flagcdn.com/w20/us.png" },
    { value: "CA", label: "Canada", code: "ca", flag: "https://flagcdn.com/w20/ca.png" },
    { value: "GB", label: "United Kingdom", code: "gb", flag: "https://flagcdn.com/w20/gb.png" },
    { value: "FR", label: "France", code: "fr", flag: "https://flagcdn.com/w20/fr.png" },
    { value: "DE", label: "Germany", code: "de", flag: "https://flagcdn.com/w20/de.png" },
    { value: "IN", label: "India", code: "in", flag: "https://flagcdn.com/w20/in.png" },
    { value: "AU", label: "Australia", code: "au", flag: "https://flagcdn.com/w20/au.png" },
    { value: "JP", label: "Japan", code: "jp", flag: "https://flagcdn.com/w20/jp.png" },
    { value: "CN", label: "China", code: "cn", flag: "https://flagcdn.com/w20/cn.png" },
    { value: "BR", label: "Brazil", code: "br", flag: "https://flagcdn.com/w20/br.png" },
    { value: "ZA", label: "South Africa", code: "za", flag: "https://flagcdn.com/w20/za.png" },
    { value: "RU", label: "Russia", code: "ru", flag: "https://flagcdn.com/w20/ru.png" },
    { value: "IT", label: "Italy", code: "it", flag: "https://flagcdn.com/w20/it.png" },
    { value: "ES", label: "Spain", code: "es", flag: "https://flagcdn.com/w20/es.png" },
    { value: "MX", label: "Mexico", code: "mx", flag: "https://flagcdn.com/w20/mx.png" },
    { value: "NG", label: "Nigeria", code: "ng", flag: "https://flagcdn.com/w20/ng.png" },
    { value: "KR", label: "South Korea", code: "kr", flag: "https://flagcdn.com/w20/kr.png" },
    { value: "AR", label: "Argentina", code: "ar", flag: "https://flagcdn.com/w20/ar.png" },
    { value: "NL", label: "Netherlands", code: "nl", flag: "https://flagcdn.com/w20/nl.png" },
    { value: "SE", label: "Sweden", code: "se", flag: "https://flagcdn.com/w20/se.png" },
  ];
  
